### ISSUE TITLE
如何更改主题？g3-lolllipop.js中未找到theme相关内容。

### ISSUE THREAD

**Issue by cheeseandgirl** [G3js/g3-lollipop#1]

**Comment by phoeguo** [comment]
The color scheme setter/getter of lollipops or domains are at

https://github.com/G3viz/g3lollipop.js/blob/8427d72e4e9dfb3d9aee00efd38e1240775f0d6a/dist/g3-lollipop.js#L2190-L2191

https://github.com/G3viz/g3lollipop.js/blob/8427d72e4e9dfb3d9aee00efd38e1240775f0d6a/dist/g3-lollipop.js#L2228-L2229

Actually, the codes related to color schemes setter/getter are in `src/lollipop/lollipop.js`

https://github.com/G3viz/g3lollipop.js/blob/8427d72e4e9dfb3d9aee00efd38e1240775f0d6a/src/lollipop/lollipop.js#L1243-L1245

https://github.com/G3viz/g3lollipop.js/blob/8427d72e4e9dfb3d9aee00efd38e1240775f0d6a/src/lollipop/lollipop.js#L1282-L1283
